export const colors = {
  primary: '#facc15',
  secondary: '#F5F5F5',
  accent: '#facc15',
  accentDark: '#ca9e04',
  accentLight: '#FEF9C3',
  accentText: '#0A0A0A',
  background: '#FFFFFF',
  surface: '#F5F5F5',
  surfaceElevated: '#FAFAFA',
  textPrimary: '#0A0A0A',
  textSecondary: '#666666',
  textTertiary: '#999999',
  textInverse: '#FFFFFF',
  border: '#E5E5E5',
  borderStrong: '#D0D0D0',
  disabled: '#BBBBBB',
  success: '#16a34a',
  warning: '#f59e0b',
  error: '#dc2626',
  overlay: 'rgba(0, 0, 0, 0.5)',
  gold: '#f59e0b',
  goldBg: '#FFFBEB',
  cardBg: '#F0F0F0',
} as const;

export type ColorKey = keyof typeof colors;
